name: .NET Core Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.101
    - name: Install dependencies
      run: dotnet restore "ValidationAdapter/ValidationAdapter.sln"
    - name: Build
      run: dotnet build "ValidationAdapter/ValidationAdapter.sln" --configuration Release --no-restore
    - name: Test
      run: dotnet test "ValidationAdapter/ValidationAdapter.sln" --no-restore --verbosity normal
